org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

java_version=25

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.9

# Mod Properties
mod_version=1.2
maven_group=com.nemonotfound.nemos.night.progression
archives_base_name=nemos-night-progression
mod_id=nemos_night_progression
mod_name=Nemo's Night Progression

# Dependencies
fabric_api_version=0.160.5+26.3
mixin_extras_version=0.5.5

# Upload
curseforge_project_id=1294916
modrinth_project_id=nemos-night-progression
