# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.3
group=com.nemonotfound.nemos.night.progression
java_version=25

# Common
minecraft_version=26.2
mod_name=Nemo's Night Progression
mod_author=Nemo
mod_id=nemos_night_progression
mod_id_jar=nemos-night-progression
license=MIT
credits=Nemo
description=Sleeping now truly skips time. Furnaces smelt, crops grow, and the world progresses as if time had passed normally.
minecraft_version_range=[26.2]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# Fabric
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Upload
curseforge_project_id=1294916
modrinth_project_id=nemos-night-progression